name: Run Amazon Scraper

on:
  schedule:
    - cron: "22 16 * * *"   # runs every day at 16:41 IST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install notebook pandas beautifulsoup4 openpyxl requests
      - name: Run Jupyter Notebook
        run: jupyter nbconvert --to notebook --execute amazon_scrap.ipynb --output executed_notebook.ipynb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: amazon-scraper-output
          path: data.csv   # make sure your notebook actually writes data.csv
