name: Run Amazon Scraper

on:
  schedule:
    # रोज़ाना सुबह 11:00 AM IST (Indian Time = UTC+5:30)
    - cron: "30 5 * * *"   # 5:30 UTC = 11:00 IST
  workflow_dispatch:      # manually run option

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true
        pip install beautifulsoup4 pandas openpyxl

    - name: Run scraper
      run: python amazon_scraper.py

    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: scraper-output
        path: |
          *.csv
          *.xlsx
          output/
