name: Run Amazon Scraper

on:
  schedule:
    - cron: "23 6 * * *"   # runs every day at 11:53 AM IST
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  artifacts: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug: log timestamps (UTC + IST)
        run: |
          echo "UTC: $(date -u +"%Y-%m-%d %H:%M:%S %Z")" > run_timestamps.txt
          echo "IST: $(TZ='Asia/Kolkata' date +"%Y-%m-%d %H:%M:%S %Z")" >> run_timestamps.txt
          cat run_timestamps.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install notebook pandas beautifulsoup4 openpyxl requests

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute amazon_scrap.ipynb --output executed_notebook.ipynb || true
          if [ -f data.csv ]; then echo "data.csv found"; else echo "data.csv NOT found"; fi

      - name: Upload artifact (debug + output)
        uses: actions/upload-artifact@v4
        with:
          name: amazon-scraper-output
          path: |
            data.csv
            run_timestamps.txt
            executed_notebook.ipynb
