name: Run Amazon Scraper

on:
  schedule:
    - cron: "* * * * *"   # runs every minute
  workflow_dispatch:       # allows manual run from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run scraper script
        run: python amazon_scrap.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: amazon-scraper-output
          path: ./output/   # change this to your script’s output folder
