name: Run Scrapers

on:
  schedule:
    - cron: "47 14 * * *"   # runs every day at 20:17 IST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install notebook pandas beautifulsoup4 openpyxl requests

      - name: Run Amazon Notebook
        run: jupyter nbconvert --to notebook --execute "amazon_scrap.ipynb" --output executed_amazon.ipynb

      - name: Run Flipkart Notebook
        run: jupyter nbconvert --to notebook --execute "Flipkart_scrap.ipynb" --output executed_flipkart.ipynb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraper-outputs
          path: |
            data.csv            # adjust if your notebooks save different files
            flipkart_data.csv   # example: Flipkart output file
