name: Run Amazon Scraper 

on:
  schedule:
    - cron: "30 5 * * *"   # रोज़ाना 11:00 AM IST
  workflow_dispatch:       # manually run करने का option

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      env:
        EMAIL_ADDRESS: ${{ secrets.Priyanshkhandelwal946215@gmail.com }}
        EMAIL_PASSWORD: ${{ secrets.iksg bgeq ylly gyyz }}
      run: python amazon_scrap.py

    - name: Upload output (Excel file)
      uses: actions/upload-artifact@v3
      with:
        name: amazon-products
        path: amazon_products.xlsx
